<?php $randomPlayerList = rand(0, 10000); ?>
<?php $randomPlugins = rand(0, 10000); ?>
<?php echo $args['before_widget']; ?>
<?php echo $args['before_title'] . $instance['title'] . $args['after_title']; ?>
<p>
<?php if (isset($instance['show_status']) && $instance['show_status'] == 'on'): ?>
    <?php _e("Status", 'mcstatus'); ?>: <span style="color:red;font-weight:bold"><?php _e("Offline", 'mcstatus'); ?></span><br>
<?php endif; ?>

<?php if (isset($instance['show_host']) && $instance['show_host'] == 'on'): ?>
    <?php _e("Host", 'mcstatus'); ?>: <strong><?php echo $instance['host'], ':', $instance['port']; ?></strong><br>
<?php endif; ?>

<?php if (isset($instance['website']) && $instance['website']): ?>
    <a href="<?php echo $instance['website']; ?>"><?php _e("Website", 'mcstatus'); ?></a><br>
<?php endif; ?>

</p>

<?php echo $args['after_widget']; ?>
