<?php $randomPlayerList = rand(0, 10000); ?>
<?php $randomPlugins = rand(0, 10000); ?>
<?php echo $args['before_widget']; ?>
<?php echo $args['before_title'] . $instance['title'] . $args['after_title']; ?>
<p>
    <?php _e("Status", 'mcstatus'); ?>: <span style="color:green;font-weight:bold">Работает</span><br>

    <?php if (isset($instance['show_host']) && $instance['show_host'] == 'on'): ?>
        <?php _e("Host", 'mcstatus'); ?>: <strong><?php echo $server['server']['host'], ':', $server['server']['port']; ?></strong><br>
    <?php endif; ?>

    <?php if (isset($instance['show_version']) && $instance['show_version']): ?>
        <?php _e("Version", 'mcstatus'); ?>: <strong><?php echo $server['server']['version']['name']; ?></strong><br>
    <?php endif; ?>

    <?php if (isset($instance['website']) && $instance['website']): ?>
        <a href="<?php echo $instance['website']; ?>"><?php _e("Website", 'mcstatus'); ?></a><br>
    <?php endif; ?>

    <?php if (isset($instance['dynmap']) && $instance['dynmap']): ?>
        <a href="<?php echo $instance['dynmap']; ?>"><?php _e("DynMap", 'mcstatus'); ?></a><br>
    <?php endif; ?>

    <?php if (isset($instance['show_plugins']) && $instance['show_plugins']): ?>
        <?php if (count($server['plugins']) > 0) : ?>
        <a href="javascript:toggleMcsList(<?php echo $randomPlugins; ?>);"><?php _e("Plugins", 'mcstatus'); ?></a>:
            <strong><?php echo count($server['plugins']); ?></strong><br>
        <?php else : ?>
            <?php _e("Plugins: <strong>Not found</strong>", 'mcstatus'); ?><br>
        <?php endif; ?>
    <?php endif; ?>

    <?php if ($server['plugins'] > 0 && isset($instance['show_plugins']) && $instance['show_plugins']) : ?>
    <span id="mcs_list_<?php echo $randomPlugins; ?>" style="display:none">
            <?php foreach ($server['plugins'] as $plugin) : ?>
        <span>- <?php echo $plugin['name']; ?></span><br>
        <?php endforeach; ?>
        </span>
    <?php endif; ?>

    <?php if ($server['players'] > 0 && isset($instance['show_players']) && $instance['show_players'] == 'on') : ?>
    <a href="javascript:toggleMcsList(<?php echo $randomPlayerList; ?>);">Игроки</a>:
    <strong><?php echo $server['server']['players_online']; ?>/<?php echo $server['server']['players_max']; ?></strong><br>
    <?php else : ?>
    <?php if (isset($instance['show_players']) && $instance['show_players']) : ?>
        <?php _e("Players", 'mcstatus'); ?>: <strong><?php echo $server['server']['players_online']; ?>/<?php echo $server['server']['players_max']; ?></strong>
        <?php endif; ?>
    <?php endif; ?>

    <?php if ($server['players'] > 0 && isset($instance['show_players']) && $instance['show_players']) : ?>
    <span id="mcs_list_<?php echo $randomPlayerList; ?>" style="margin-top:5px;<?php echo (isset($instance['show_auto_players']) && $instance['show_auto_players'] == 'on') ? 'display:block' : 'display:none'; ?> ">
            <?php foreach ($server['players'] as $player) : ?>
                <?php echo $player['name']; ?>
        <?php endforeach; ?>
        </span>
    <?php endif; ?>
</p>

<?php echo $args['after_widget']; ?>

<script type="text/javascript">
    function toggleMcsList(random) {
        if (document.getElementById('mcs_list_' + random).style.display == 'none') {
            document.getElementById('mcs_list_' + random).style.display = 'block';
        } else {
            document.getElementById('mcs_list_' + random).style.display = 'none';
        }
    }
</script>
